pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/suryat221/LeaveManagment.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building the project...'
                // Add actual build commands here, e.g., Maven, Gradle, npm, etc.
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                // Add test commands, e.g., unit tests or integration tests.
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
                // Add deployment commands here.
            }
        }
    }
}

